name: Run Morse Tests

on:
  push:
    branches:
      - 'test_branch'

jobs:
  Set_the_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install g++ compiler
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Verify g++ version
        run: g++ --version

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Verify Python version
        run: python3 -V

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pybind11

      - name: Create the morse module from C++ for Python
        run: |
          cd morse/cppToPythonModule/
          bash build.sh

      - name: Check the shared object that was created
        run: |
          cd morse
          ls -la morse.so

      - name: Run the program
        run: python3 morse.py
