name: Run Morse Tests

on:
  push:
    branches:
      - 'test_branch'

jobs:
  Run-the-program:
    name: Execute the programm
    runs-on: ubuntu-latest
    steps:
      - name: Install pybind11
        run: |
          python3 -m pip install --upgrade pip
          pip install pybind11
      
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Create the morse module from C++ for Python
        run: |
          cd cppToPythonModule
          bash build.sh

      - name: Check the shared object that was created
        run: |
          ls -la morseModule.so

      - name: Run the program
        run: |
          python3 morse.py
          
