name: Run Morse Tests

on:
  push:
    branches:
      - 'improvements-branch'

jobs:
  Run-test-case-scenarios:
    name: Set OS
    runs-on: ubuntu-latest

    steps:
      - name: Install pybind11
        run: |
          python3 -m pip install --upgrade pip
          pip install pybind11
          pip install pytest

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create the morse module from C++ for Python
        run: |
          cd src/services/cppToPythonModule
          bash build.sh

      - name: Check the shared object that was created
        run: |
          ls -la src/morseModule.so

      - name: Run the program
        run: |
          cd tests/
          pytest testMorseParser.py
          
