name: Run Morse Tests

on:
  push:
    branches:
      - 'test_branch'

jobs:
  set-the-env:
    name: Set the requirements for the environment
    runs-on: ubuntu-latest
    steps:
      - name: Install g++ compiler
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pybind11
        run: |
          python3 -m pip install --upgrade pip
          pip install pybind11

      - name: Verify g++ and Python versions
        run: |
          g++ --version
          python3 -V

  Run-the-program:
    needs: [set-the-env]
    name: Execute the programm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Create the morse module from C++ for Python
        run: |
          cd cppToPythonModule
          bash build.sh

      - name: Check the shared object that was created
        run: |
          ls -la morse.so

      - name: Run the program
        run: |
          python3 morse.py
          
