name: Run Morse Tests

on:
  push:
    branches:
      - 'improvements-branch'

jobs:
  run-tests:
    name: Set env and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Install pybind11
        run: |
          python3 -m pip install --upgrade pip
          pip install pybind11
          pip install pytest

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create the morse module from C++ for Python
        run: |
          cd src/services/cppToPythonModule
          bash build.sh

      - name: Check the shared object that was created
        run: |
          ls -la src/services/cppToPythonModule/morseModule.so

      - name: Run unit tests
        run: |
          cd tests/
          pytest testMorseParser.py

  jenkins-docker:
    needs: run-tests
    name: Run jenkins in docker container
    runs-on: ubuntu-latest

    steps:
      - name: Pull the Jenkins image from the Github Packages
        run: docker pull ghcr.io/marrinosnis/jenkins-python-pybind11:latest

      - name: Run the docker compose to build the container from the pulled image
        run: |
          docker compose up -d
